"""
LaTeX Resume Parser
==================
Converts LaTeX resume → Master Resume JSON format

Parses LaTeX documents generated by latex_renderer.py
"""

import re
from typing import Dict, Any, List, Optional


class LaTeXParser:
    """Parse LaTeX resume into structured JSON format"""
    
    def __init__(self):
        self.content = ""
    
    def parse(self, latex_content: str) -> Dict[str, Any]:
        """
        Parse LaTeX resume content into master resume JSON format
        
        Args:
            latex_content: LaTeX document as string
            
        Returns:
            Master resume dictionary matching the expected JSON format
        """
        self.content = latex_content
        
        # Extract sections - CRITICAL: Parse ALL sections to prevent data loss
        profile = self._parse_profile()
        summary = self._parse_summary()
        skills = self._parse_skills()
        experience = self._parse_experience()
        projects = self._parse_projects()
        education = self._parse_education()
        
        return {
            "profile": profile,
            "summary": summary,  # Professional Summary section
            "skills": skills,
            "experience": experience,
            "projects": projects,
            "education": education if education else []
        }
    
    def _parse_profile(self) -> Dict[str, Any]:
        """Extract profile information from header"""
        profile = {}
        
        # Extract name (usually in \textbf{} in center environment)
        name_match = re.search(r'\\textbf\{([^}]+)\}', self.content)
        if name_match:
            profile['name'] = self._clean_latex(name_match.group(1))
        
        # Extract headline (usually right after name)
        headline_match = re.search(r'\\textbf\{[^}]+\}\\\\[4pt]([^\\\\]+)\\\\[4pt]', self.content)
        if headline_match:
            profile['headline'] = self._clean_latex(headline_match.group(1))
        
        # Extract contact info (email, phone, location)
        contact_pattern = r'([a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,})|(\+?[0-9\-\(\)\s]+)|([A-Za-z\s,]+(?:India|USA|United States|Canada|UK|United Kingdom))'
        contact_matches = re.findall(contact_pattern, self.content)
        
        for match in contact_matches:
            if match[0] and '@' in match[0]:  # Email
                profile['email'] = match[0]
            elif match[1] and any(c.isdigit() for c in match[1]):  # Phone
                profile['phone'] = match[1].strip()
            elif match[2] and len(match[2].strip()) > 3:  # Location
                profile['location'] = match[2].strip()
        
        # Extract LinkedIn and GitHub
        linkedin_match = re.search(r'linkedin\.com/in/([^\s\$]+)', self.content, re.IGNORECASE)
        if linkedin_match:
            profile['linkedin'] = f"linkedin.com/in/{linkedin_match.group(1)}"
        
        github_match = re.search(r'github\.com/([^\s\$]+)', self.content, re.IGNORECASE)
        if github_match:
            profile['github'] = f"github.com/{github_match.group(1)}"
        
        return profile
    
    def _parse_skills(self) -> List[Dict[str, Any]]:
        """Extract skills from Technical Skills section"""
        skills = []
        
        # Find Technical Skills section - handle both \section{} and \section*{}
        skills_section = re.search(
            r'\\section\*?\{[^}]*[Tt]echnical[^}]*[Ss]kills[^}]*\}(.*?)(?=\\section|\Z|\\end)', 
            self.content, 
            re.DOTALL | re.IGNORECASE
        )
        if not skills_section:
            return skills
        
        skills_text = skills_section.group(1)
        
        # Remove empty lines and whitespace
        skills_text = skills_text.strip()
        if not skills_text:
            return skills
        
        # Handle categorized format: \textbf{Category:} skill1, skill2 \\
        # Extract all skills from categorized lists
        skill_names = []
        
        # Pattern 1: \textbf{Category:} skill1, skill2 \\
        category_pattern = r'\\textbf\{[^}]+\}:\s*([^\\\\]+)'
        category_matches = re.findall(category_pattern, skills_text)
        for match in category_matches:
            # Clean the match first
            clean_match = re.sub(r'\\\\', ' ', match)  # Replace \\ with space
            clean_match = re.sub(r'\s+', ' ', clean_match)  # Normalize whitespace
            # Split by comma and clean
            category_skills = [s.strip() for s in clean_match.split(',') if s.strip() and len(s.strip()) > 1]
            skill_names.extend(category_skills)
        
        # Pattern 2: Simple comma-separated list (if no categories found)
        if not skill_names:
            # Remove LaTeX commands but preserve content
            clean_text = re.sub(r'\\textbf\{[^}]+\}:\s*', '', skills_text)
            clean_text = re.sub(r'\\[a-zA-Z]+\{?[^}]*\}?', '', clean_text)
            clean_text = re.sub(r'\{|\}', '', clean_text)
            clean_text = re.sub(r'\$[^$]*\$', '', clean_text)
            clean_text = re.sub(r'\\\[.*?\\\]', '', clean_text)
            clean_text = re.sub(r'\\\\', ' ', clean_text)  # Replace \\ with space
            
            # Split by comma, semicolon, or newline
            for delimiter in [',', ';', '\n']:
                if delimiter in clean_text:
                    skill_names = [s.strip() for s in clean_text.split(delimiter) if s.strip() and len(s.strip()) > 1]
                    break
        
        # Pattern 3: Extract capitalized tech terms
        if not skill_names:
            skill_names = re.findall(r'\b[A-Z][a-zA-Z0-9]+(?:\.[A-Z][a-zA-Z0-9]+)?\b', skills_text)
        
        # Convert to expected format with tags
        for skill_name in skill_names:
            skill_name = self._clean_latex(skill_name).strip()
            if skill_name and len(skill_name) > 1:
                tags = self._infer_skill_tags(skill_name)
                skills.append({
                    "name": skill_name,
                    "tags": tags
                })
        
        return skills
    
    def _parse_summary(self) -> str:
        """Extract Professional Summary section - CRITICAL: Prevent data loss"""
        # Find Professional Summary section - handle both \section{} and \section*{}
        summary_section = re.search(
            r'\\section\*?\{[^}]*[Pp]rofessional[^}]*[Ss]ummary[^}]*\}(.*?)(?=\\section\{|\Z|\\end\{document\})', 
            self.content, 
            re.DOTALL | re.IGNORECASE
        )
        if not summary_section:
            return ""
        
        summary_text = summary_section.group(1).strip()
        if not summary_text:
            return ""
        
        # Remove LaTeX comments
        summary_text = re.sub(r'%.*?$', '', summary_text, flags=re.MULTILINE)
        
        # Clean LaTeX commands and extract plain text
        summary = self._clean_latex(summary_text)
        # Remove extra whitespace but preserve sentence structure
        summary = ' '.join(summary.split())
        
        return summary
    
    def _parse_experience(self) -> List[Dict[str, Any]]:
        """Extract experience entries"""
        experience = []
        
        # Find Professional Experience section - handle both \section{} and \section*{}
        # Use a more robust pattern that captures everything until the next \section{ or \end{document}
        exp_section = re.search(
            r'\\section\*?\{[^}]*[Ee]xperience[^}]*\}(.*?)(?=\\section\{|\Z|\\end\{document\})', 
            self.content, 
            re.DOTALL | re.IGNORECASE
        )
        if not exp_section:
            return experience
        
        exp_text = exp_section.group(1).strip()
        if not exp_text:
            return experience
        
        # DEBUG: Show what text we're searching
        print(f"[PARSER DEBUG] Experience section text length: {len(exp_text)}")
        print(f"[PARSER DEBUG] First 200 chars: {exp_text[:200]}")
        print(f"[PARSER DEBUG] Last 200 chars: {exp_text[-200:]}")
        
        # Better approach: Find all \textbf{} entries and their following content
        # Pattern: \textbf{Role} \\ Company \hfill Duration \begin{itemize}...\end{itemize}
        # Or: \textbf{Role} \\ Company \hfill Duration (without itemize)
        
        # Find all \textbf{} positions
        textbf_matches = list(re.finditer(r'\\textbf\{([^}]+)\}', exp_text))
        
        print(f"[PARSER DEBUG] Found {len(textbf_matches)} \\textbf{{}} matches in experience section")
        for i, match in enumerate(textbf_matches):
            print(f"[PARSER DEBUG]   Match {i+1}: '{match.group(1)}' at position {match.start()}")
        
        if not textbf_matches:
            return experience
        
        # Process each \textbf{} entry
        for idx, match in enumerate(textbf_matches):
            role = self._clean_latex(match.group(1)).strip()
            
            # Get text after this \textbf{} until next \textbf{} or end
            start_pos = match.end()
            if idx + 1 < len(textbf_matches):
                end_pos = textbf_matches[idx + 1].start()
            else:
                end_pos = len(exp_text)
            
            entry_text = exp_text[start_pos:end_pos].strip()
            
            # Extract company and duration
            # Pattern: \\ Company, Location \hfill Duration
            # Or: \\ Company \hfill Duration
            # Or: Company, Location \hfill Duration (without \\)
            company_duration_match = re.search(r'(?:\\\\\s*)?([^\\]+?)\s+\\hfill\s+([^\\\\]+)', entry_text)
            if company_duration_match:
                company_line = self._clean_latex(company_duration_match.group(1)).strip()
                duration = self._clean_latex(company_duration_match.group(2)).strip()
                
                # Extract company name (before comma if location present)
                if ',' in company_line:
                    company = company_line.split(',')[0].strip()
                else:
                    company = company_line
            else:
                # Fallback: look for company pattern without \hfill
                # Pattern: \\ Company, Location -- Duration
                company_match = re.search(r'(?:\\\\\s*)?([A-Z][^\\]+?)(?:,\s*[A-Z][^\\]*)?\s+--\s+([^\\\\]+)', entry_text)
                if company_match:
                    company_line = self._clean_latex(company_match.group(1)).strip()
                    duration = self._clean_latex(company_match.group(2)).strip()
                    if ',' in company_line:
                        company = company_line.split(',')[0].strip()
                    else:
                        company = company_line
                else:
                    # Last fallback: just find company name
                    company_match = re.search(r'(?:\\\\\s*)?([A-Z][a-zA-Z\s&]+?)(?:,\s*[A-Z]|\s+--|\Z)', entry_text)
                    company = self._clean_latex(company_match.group(1)).strip() if company_match else ""
                    duration_match = re.search(r'--\s*([^\\\\]+)', entry_text)
                    duration = self._clean_latex(duration_match.group(1)).strip() if duration_match else ""
            
            # Extract bullets - be more flexible with itemize environment
            bullets = []
            # Look for itemize blocks
            itemize_blocks = re.findall(r'\\begin\{itemize\}(.*?)\\end\{itemize\}', entry_text, re.DOTALL)
            for block in itemize_blocks:
                bullet_matches = re.findall(r'\\item\s+(.+?)(?=\\item|\\end|$)', block, re.DOTALL)
                for bullet_text in bullet_matches:
                    bullet_text = self._clean_latex(bullet_text).strip()
                    if bullet_text and len(bullet_text) > 5:  # Minimum length check
                        # Generate ID and infer tags
                        bullet_id = f"exp{len(experience)+1}_b{len(bullets)+1}"
                        tags = self._infer_bullet_tags(bullet_text)
                        bullets.append({
                            "id": bullet_id,
                            "text": bullet_text,
                            "tags": tags
                        })
            
            # Also try simple \item pattern if itemize wasn't found
            if not bullets:
                bullet_matches = re.findall(r'\\item\s+([^\\\\]+)', entry_text)
                for bullet_text in bullet_matches:
                    bullet_text = self._clean_latex(bullet_text).strip()
                    if bullet_text and len(bullet_text) > 5:
                        bullet_id = f"exp{len(experience)+1}_b{len(bullets)+1}"
                        tags = self._infer_bullet_tags(bullet_text)
                        bullets.append({
                            "id": bullet_id,
                            "text": bullet_text,
                            "tags": tags
                        })
            
            # Add experience entry if we have role OR company OR bullets
            if role or company or bullets:
                exp_entry = {
                    "company": company or "Unknown Company",
                    "role": role or "Engineer",
                    "duration": duration or "",
                    "bullets": bullets
                }
                experience.append(exp_entry)
                print(f"[PARSER DEBUG] Added experience {len(experience)}: {exp_entry.get('role')} at {exp_entry.get('company')} ({len(bullets)} bullets)")
            else:
                print(f"[PARSER DEBUG] Skipped entry {idx+1}: role='{role}', company='{company}', bullets={len(bullets)}")
        
        print(f"[PARSER DEBUG] Total experiences parsed: {len(experience)}")
        return experience
    
    def _parse_projects(self) -> List[Dict[str, Any]]:
        """Extract projects"""
        projects = []
        
        # Find Projects section - handle both \section{} and \section*{}
        proj_section = re.search(
            r'\\section\*?\{[^}]*[Pp]rojects[^}]*\}(.*?)(?=\\section\{|\Z|\\end\{document\})', 
            self.content, 
            re.DOTALL | re.IGNORECASE
        )
        if not proj_section:
            return projects
        
        proj_text = proj_section.group(1).strip()
        if not proj_text:
            return projects
        
        # Split by project entries - try multiple patterns
        proj_entries = re.split(r'(?:\\noindent)?\\textbf\{([^}]+)\}', proj_text)
        
        for i in range(1, len(proj_entries), 2):
            if i + 1 >= len(proj_entries):
                break
                
            project_name = self._clean_latex(proj_entries[i])
            entry_text = proj_entries[i + 1]
            
            # Extract technologies - handle both \textit{} and inline formats
            technologies = []
            tech_match = re.search(r'\\textit\{\s*([^}]+)\s*\}', entry_text)
            if tech_match:
                tech_text = self._clean_latex(tech_match.group(1))
                technologies = [t.strip() for t in tech_text.split(',') if t.strip()]
            else:
                # Try to find technologies mentioned in bullets or description
                # Look for common tech terms near project name
                tech_keywords = ['Java', 'Python', 'Spring', 'Node', 'Express', 'Kafka', 'PostgreSQL', 'MongoDB', 'Redis', 'Docker', 'Kubernetes', 'AWS']
                found_techs = []
                for tech in tech_keywords:
                    if tech.lower() in entry_text.lower():
                        found_techs.append(tech)
                technologies = found_techs[:5]  # Limit to 5
            
            # Extract bullets - look for itemize blocks
            bullets = []
            itemize_blocks = re.findall(r'\\begin\{itemize\}(.*?)\\end\{itemize\}', entry_text, re.DOTALL)
            for block in itemize_blocks:
                bullet_matches = re.findall(r'\\item\s+(.+?)(?=\\item|$)', block, re.DOTALL)
                for bullet_text in bullet_matches:
                    bullet_text = self._clean_latex(bullet_text).strip()
                    if bullet_text and len(bullet_text) > 5:
                        bullets.append(bullet_text)
            
            # Fallback to simple \item pattern
            if not bullets:
                bullet_matches = re.findall(r'\\item\s+([^\\\\]+)', entry_text)
                for bullet_text in bullet_matches:
                    bullet_text = self._clean_latex(bullet_text).strip()
                    if bullet_text and len(bullet_text) > 5:
                        bullets.append(bullet_text)
            
            # Infer tags from project name and technologies
            tags = self._infer_project_tags(project_name, technologies)
            
            # Add project if we have name OR bullets
            if project_name or bullets:
                projects.append({
                    "id": f"proj{len(projects)+1}",
                    "name": project_name or "Project",
                    "description": "",  # Not typically in LaTeX output
                    "tags": tags,
                    "technologies": technologies,
                    "bullets": bullets
                })
        
        return projects
    
    def _parse_education(self) -> List[Dict[str, Any]]:
        """Extract education - handles multiple formats"""
        education = []
        
        edu_section = re.search(r'\\section\*?\{Education\}(.*?)(?=\\section|\Z|\\end)', self.content, re.DOTALL | re.IGNORECASE)
        if not edu_section:
            return education
        
        edu_text = edu_section.group(1).strip()
        if not edu_text:
            return education
        
        # Pattern 1: \textbf{Institution} \\ Degree (user's format)
        # Match: \textbf{...} followed by \\ and then text
        # Note: In raw strings, \\\\ matches literal \\ in the text
        pattern1 = re.finditer(r'\\textbf\{([^}]+)\}\s*\\\\\s*([^\n]+)', edu_text)
        for match in pattern1:
            institution = self._clean_latex(match.group(1)).strip()
            degree_line = self._clean_latex(match.group(2)).strip()
            
            # Extract year and GPA from degree line if present
            year_match = re.search(r'(\d{4})', degree_line)
            year = year_match.group(1) if year_match else ""
            
            gpa_match = re.search(r'GPA:\s*([^\s,]+)', degree_line)
            gpa = gpa_match.group(1) if gpa_match else ""
            
            # Remove year and GPA from degree text
            degree = degree_line
            if year:
                degree = re.sub(r',?\s*\d{4}', '', degree).strip()
            if gpa_match:
                degree = re.sub(r'GPA:\s*[^\s,]+', '', degree).strip()
            degree = degree.strip(',').strip()
            
            if institution or degree:
                education.append({
                    "degree": degree or "",
                    "institution": institution or "",
                    "year": year,
                    "gpa": gpa
                })
                continue  # Found match, don't try other patterns
        
        # Pattern 2: \noindent\textbf{Degree} \\ Institution
        if not education:
            pattern2 = re.finditer(r'(?:\\noindent)?\\textbf\{([^}]+)\}\s*\\\\\s*([^\n\\\\]+)', edu_text)
            for match in pattern2:
                degree = self._clean_latex(match.group(1)).strip()
                institution_line = self._clean_latex(match.group(2)).strip()
                
                # Extract institution (before comma if location present)
                institution = institution_line.split(',')[0].strip() if ',' in institution_line else institution_line
                
                # Extract year and GPA
                year_match = re.search(r',\s*(\d{4})', institution_line)
                year = year_match.group(1) if year_match else ""
                
                gpa_match = re.search(r'GPA:\s*([^\s,]+)', institution_line)
                gpa = gpa_match.group(1) if gpa_match else ""
                
                if degree or institution:
                    education.append({
                        "degree": degree or "",
                        "institution": institution or "",
                        "year": year,
                        "gpa": gpa
                    })
        
        # Pattern 3: Simple format - just \textbf{Institution} \\ Degree (fallback)
        if not education:
            # Try to find any \textbf{} followed by \\
            simple_match = re.search(r'\\textbf\{([^}]+)\}\s*\\\\\s*([^\n]+)', edu_text)
            if simple_match:
                first = self._clean_latex(simple_match.group(1)).strip()
                second = self._clean_latex(simple_match.group(2)).strip()
                
                # Heuristic: if first contains "Institute", "University", "College" -> institution
                # Otherwise assume it's degree
                if any(word in first.lower() for word in ['institute', 'university', 'college', 'school']):
                    education.append({
                        "degree": second,
                        "institution": first,
                        "year": "",
                        "gpa": ""
                    })
                else:
                    education.append({
                        "degree": first,
                        "institution": second,
                        "year": "",
                        "gpa": ""
                    })
        
        return education
    
    def _clean_latex(self, text: str) -> str:
        """Remove LaTeX commands and special characters"""
        # Remove LaTeX commands
        text = re.sub(r'\\[a-zA-Z]+\{?[^}]*\}?', '', text)
        # Remove braces
        text = re.sub(r'\{|\}', '', text)
        # Remove special LaTeX characters
        text = text.replace('$|$', '|')
        text = text.replace('\\[4pt]', ' ')
        text = text.replace('\\vspace{4pt}', ' ')
        # Clean up whitespace
        text = ' '.join(text.split())
        return text.strip()
    
    def _infer_skill_tags(self, skill_name: str) -> List[str]:
        """Infer tags for a skill based on its name"""
        skill_lower = skill_name.lower()
        tags = []
        
        # AI/ML tags
        if any(x in skill_lower for x in ['tensorflow', 'pytorch', 'keras', 'ml', 'machine learning', 'deep learning', 'neural', 'ai', 'opencv', 'cv', 'computer vision', 'nlp', 'bert', 'gpt']):
            tags.extend(['ai', 'ml'])
        
        # Backend tags
        if any(x in skill_lower for x in ['python', 'java', 'go', 'node', 'fastapi', 'django', 'flask', 'spring', 'rest', 'api', 'microservice', 'postgres', 'mysql', 'redis', 'mongodb', 'elasticsearch']):
            tags.append('backend')
        
        # Frontend tags
        if any(x in skill_lower for x in ['react', 'vue', 'angular', 'javascript', 'typescript', 'html', 'css', 'frontend']):
            tags.append('frontend')
        
        # DevOps tags
        if any(x in skill_lower for x in ['docker', 'kubernetes', 'k8s', 'aws', 'gcp', 'azure', 'terraform', 'ansible', 'jenkins', 'ci/cd', 'devops', 'infrastructure']):
            tags.append('devops')
        
        # Database tags
        if any(x in skill_lower for x in ['postgres', 'mysql', 'mongodb', 'redis', 'elasticsearch', 'database', 'sql', 'nosql']):
            tags.append('database')
        
        # Cloud tags
        if any(x in skill_lower for x in ['aws', 'gcp', 'azure', 'cloud']):
            tags.append('cloud')
        
        # Full stack
        if 'fullstack' in skill_lower or 'full stack' in skill_lower:
            tags.append('fullstack')
        
        # Data tags
        if any(x in skill_lower for x in ['data', 'etl', 'spark', 'hadoop', 'pandas', 'numpy']):
            tags.append('data')
        
        return tags if tags else ['general']
    
    def _infer_bullet_tags(self, bullet_text: str) -> List[str]:
        """Infer tags for a bullet point"""
        bullet_lower = bullet_text.lower()
        tags = []
        
        # Use similar logic as skill tags
        if any(x in bullet_lower for x in ['api', 'rest', 'microservice', 'backend', 'server']):
            tags.append('backend')
        if any(x in bullet_lower for x in ['react', 'frontend', 'ui', 'ux', 'javascript']):
            tags.append('frontend')
        if any(x in bullet_lower for x in ['docker', 'kubernetes', 'aws', 'devops', 'infrastructure', 'ci/cd']):
            tags.append('devops')
        if any(x in bullet_lower for x in ['ai', 'ml', 'machine learning', 'tensorflow', 'pytorch', 'opencv', 'cv']):
            tags.extend(['ai', 'ml'])
        if any(x in bullet_lower for x in ['database', 'postgres', 'mysql', 'mongodb', 'redis']):
            tags.append('database')
        if any(x in bullet_lower for x in ['distributed', 'scalable', 'microservice']):
            tags.append('distributed-systems')
        
        return tags if tags else ['general']
    
    def _infer_project_tags(self, project_name: str, technologies: List[str]) -> List[str]:
        """Infer tags for a project"""
        tags = []
        name_lower = project_name.lower()
        tech_lower = ' '.join(technologies).lower()
        combined = name_lower + ' ' + tech_lower
        
        # Similar inference logic
        if any(x in combined for x in ['ai', 'ml', 'machine learning', 'tensorflow', 'pytorch', 'opencv', 'cv', 'neural']):
            tags.extend(['ai', 'ml'])
        if any(x in combined for x in ['backend', 'api', 'rest', 'server', 'microservice']):
            tags.append('backend')
        if any(x in combined for x in ['frontend', 'react', 'ui', 'web']):
            tags.append('frontend')
        if any(x in combined for x in ['devops', 'docker', 'kubernetes', 'infrastructure']):
            tags.append('devops')
        if any(x in combined for x in ['fullstack', 'full stack']):
            tags.append('fullstack')
        if any(x in combined for x in ['data', 'etl', 'analytics']):
            tags.append('data')
        
        return tags if tags else ['general']


def parse_latex_resume(latex_content: str) -> Dict[str, Any]:
    """
    Convenience function to parse LaTeX resume
    
    Usage:
        with open('resume.tex', 'r') as f:
            master_resume = parse_latex_resume(f.read())
    """
    parser = LaTeXParser()
    return parser.parse(latex_content)
